# Generated by Django 4.0 on 2021-12-27 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='author_id',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='quest',
            name='school_id',
        ),
        migrations.AddField(
            model_name='quest',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='latte.category'),
        ),
        migrations.AddField(
            model_name='quest',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='latte.school'),
        ),
    ]
