# Generated by Django 4.0 on 2021-12-28 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0002_remove_quest_author_id_remove_quest_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
