# Generated by Django 4.0 on 2021-12-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0003_alter_quest_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='title',
            new_name='todo_quest',
        ),
    ]
