# Generated by Django 4.0 on 2021-12-28 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('latte', '0005_alter_quest_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='category',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='latte.category'),
        ),
        migrations.AlterField(
            model_name='quest',
            name='school',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='latte.school'),
        ),
    ]
